"""Regenerate ``src/athletevalue/data/pinned_artifacts.json`` from a populated cache.

Run after the live regression suite passes and the documented numbers have been
checked against the same cache::

    uv run python scripts/pin_artifacts.py            # default cache directory
    uv run python scripts/pin_artifacts.py --cache-dir /path/to/cache

Every raw artifact in the manifest is pinned except listings that change by
design (the EADA file list). The script re-hashes each file rather than trusting
the manifest, and refuses to write if any file is missing or altered.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from athletevalue.sources.cache import ArtifactCache

OUTPUT = Path(__file__).resolve().parents[1] / "src/athletevalue/data/pinned_artifacts.json"
NEVER_PINNED = ("raw/eada/fileList.json",)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cache-dir", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    cache = ArtifactCache(args.cache_dir) if args.cache_dir else ArtifactCache.default()

    artifacts: dict[str, dict[str, object]] = {}
    problems = []
    for relative, entry in sorted(cache.manifest().items()):
        if relative.startswith("derived/") or entry.get("kind") == "derived":
            continue
        if relative in NEVER_PINNED:
            continue
        path = cache.path_for(relative)
        if not path.exists():
            problems.append(f"{relative}: recorded but missing")
            continue
        actual = _sha256(path)
        if actual != entry["sha256"]:
            problems.append(f"{relative}: contents differ from the manifest")
            continue
        artifacts[str(entry["url"])] = {"sha256": actual, "bytes": path.stat().st_size}
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    payload = {
        "description": (
            "SHA-256 digests of the upstream files behind the documented numbers. "
            "Generated by scripts/pin_artifacts.py; do not edit by hand."
        ),
        "artifacts": dict(sorted(artifacts.items())),
    }
    args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"pinned {len(artifacts)} artifacts to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
